RealEstate/REApp/urls.py
from django.urls import path
from REApp import views

urlpatterns = [

    path('', views.home, name="home"),
    path('login/', views.login, name="login"),
    path('registration/', views.registration, name="registration"),
    path('save_registration/', views.save_registration, name="save_registration"),
    path('user_login/', views.user_login, name="user_login"),
    path('user_logout/', views.user_logout, name="user_logout"),
    path('add_property/', views.add_property, name="add_property"),
    path('save_property/', views.save_property, name="save_property"),
    path('property_list/', views.property_list, name="property_list"),
    path('my_post/', views.my_post, name="my_post"),
    path('view_post/<int:postId>/', views.view_post, name="view_post"),
    path('delete_post/<int:postId>/', views.delete_post, name="delete_post"),
    path('edit_post/<int:postId>/', views.edit_post, name="edit_post"),
    path('update_post/<int:postId>/', views.update_post, name="update_post"),
    path('search/',views.search,name='search'),
    path('fo/',views.Feed.as_view(),name="feedback")

]

RealEstate/RealEstate/urls.py
from django.contrib import admin
from django.urls import path, include
import REApp.urls
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from RealEstate import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(REApp.urls))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RealEstate/REApp/models.py
from django.db import models


# Create your models here.
class RegistrationDB(models.Model):
    UserId = models.AutoField(primary_key=True)
    Name = models.CharField(max_length=50, null=False)
    Email = models.EmailField(max_length=70, null=False,default="aa")
    Password = models.CharField(max_length=20, null=False)
    Role = models.CharField(max_length=50, null=True, blank=True)
    Account_created = models.DateTimeField(auto_now_add=True)


class PropertyDB(models.Model):
    PropertyId = models.AutoField(primary_key=True)
    Image = models.ImageField(upload_to="PropertyImage", null=True, blank=True)
    PDF = models.FileField(upload_to="PropertyPDF", null=True, blank=True)  # Add this field
    Purpose = models.CharField(max_length=20, null=True, blank=True)
    Type = models.CharField(max_length=20, null=True, blank=True)
    Title = models.CharField(max_length=50, null=True, blank=True)
    Description = models.CharField(max_length=500, null=True, blank=True)
    Price = models.IntegerField(default=0)
    Location = models.CharField(max_length=50, null=True, blank=True)
    Phone = models.PositiveBigIntegerField(null=True, blank=True)
    UserId = models.ForeignKey(RegistrationDB, on_delete=models.CASCADE)
    posted_on = models.DateTimeField(auto_now_add=True)

class Feedback(models.Model):
    Name=models.CharField(max_length=50)
    Gmail=models.EmailField(null=True)
    Message=models.CharField(max_length=250)

RealEstate/REApp/forms.py
from django import forms
from REApp.models import Feedback
class Feedback_form(forms.ModelForm):
    class Meta:
        model=Feedback
        fields = ["Name","Gmail","Message"]

RealEstate/REApp/views.py
from django.shortcuts import render, redirect
from REApp.models import RegistrationDB, PropertyDB, Feedback
from django.contrib import messages
import re
from REApp.forms import Feedback_form
from django.core.files.storage import FileSystemStorage
from django.utils.datastructures import MultiValueDictKeyError
from django.views.generic import View,CreateView
from django.urls import reverse_lazy


# Create your views here.
# logined user home page
def home(request):
    if 'userid' in request.session:
        
        profile = RegistrationDB.objects.get(UserId=request.session['userid'])
        
        return render(request,'index.html',{'profile':profile})
    else:
        return render(request, "index.html")


# class Indexview(View):
#     def get(self,request,*args,**kwargs):
#         if 'userid' in request.session:
#             profile = RegistrationDB.objects.get(UserId=request.session['userid'])
#             return render(request, "index.html", {'profile': profile})
#         else:
#             return render(request,"index.html")
    
#     def post(self,request,*args,**kwargs):
#         form=request.POST
#         print(request.POST)

# login page
def login(request):
    return render(request, "login.html")

# Registration page
def registration(request):
    return render(request, "register.html")

#registration code
from django.contrib import messages

def save_registration(request):
    if request.method == "POST":
        n = request.POST.get('name')
        e = request.POST.get('email')
        p = request.POST.get('password')
        r = request.POST.get('role')

        # Check if any of the required fields are empty
        if not (n and e and p and r):
            messages.error(request, "Please fill all the fields.")
            return redirect(registration)

        if RegistrationDB.objects.filter(Email=e).exists():
            messages.error(request, "Email Id already exists..!!")
            return redirect(registration)
        
        if not re.match(r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+])[A-Za-z\d!@#$%^&*()_+]{8,}$", p):
            messages.error(request, "Password should be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one number, and one special character.")
            return redirect(registration)

        obj = RegistrationDB(Name=n, Email=e, Password=p, Role=r)
        obj.save()
        messages.success(request, "Registration Successfully Completed..!!")
        return redirect(login)


# login code
from django.contrib import messages

def user_login(request):
    if request.method == "POST":
        un = request.POST.get('email')
        pwd = request.POST.get('password')
        
        if not un or not pwd:
            # If email or password is missing, display a message
            messages.error(request, "Please enter both email and password")
            return redirect(login)
        
        if RegistrationDB.objects.filter(Email=un, Password=pwd).exists():
            request.session['Email'] = un
            request.session['Password'] = pwd
            user = RegistrationDB.objects.get(Email=un, Password=pwd)
            request.session['userid'] = user.UserId
            messages.success(request, "Logged in Successfully..!!")
            return render(request, "index.html")
        else:
            messages.error(request, "Invalid Username or Password")
            return redirect(login)
    return redirect(login)


# user logout
def user_logout(request):
    del request.session['Email']
    del request.session['Password']
    del request.session['userid']
    return redirect(home)

# property adding
def add_property(request):
    if 'userid' in request.session:
        profile = RegistrationDB.objects.get(UserId=request.session['userid'])
        return render(request, "addProperty.html", {'profile': profile})
    else:
        return redirect(login)

# property saving to the database
def save_property(request):
    if request.method == "POST":
        pu = request.POST.get('purpose')
        ty = request.POST.get('type')
        ti = request.POST.get('title')
        de = request.POST.get('description')
        pr = request.POST.get('price')
        lo = request.POST.get('location')
        ph = request.POST.get('phone')
        uid = RegistrationDB.objects.get(UserId=request.session['userid'])
        img = request.FILES['image']
        pdf = request.FILES.get('pdf')
        obj = PropertyDB(Purpose=pu, Type=ty, Title=ti, Price=pr, Location=lo, Phone=ph, UserId=uid, Description=de, Image=img, PDF=pdf)
        obj.save()
        messages.success(request, "Property Posted Successfully")
        return redirect(home)

# list all properties
def property_list(request):
    pdata = PropertyDB.objects.all()
    if 'userid' in request.session:
        profile = RegistrationDB.objects.get(UserId=request.session['userid'])
       
        return render(request, "propertyList.html", {'profile': profile, 'pdata': pdata })
    else:
        return render(request, "propertyList.html", {'pdata': pdata})

# 

def search(request):
    if request.method=="POST":
            # price=request.POST.get("price")
            p_type=request.POST.get("type")
            location=request.POST.get("location")
            data=PropertyDB.objects.filter(Type=p_type,Location=location)
            print(data)
            print(p_type,location)
            return render(request, "propertyList.html", {'data':data})


def my_post(request):
    pdata = PropertyDB.objects.filter(UserId_id=request.session['userid'])
    if 'userid' in request.session:
        profile = RegistrationDB.objects.get(UserId=request.session['userid'])
        return render(request, "myPost.html", {'profile': profile, 'pdata': pdata})
    else:
        return redirect(home)


def view_post(request, postId):
    post = PropertyDB.objects.get(PropertyId=postId)
    if 'userid' in request.session:
        profile = RegistrationDB.objects.get(UserId=request.session['userid'])
        return render(request, "viewPost.html", {'profile': profile, 'post': post})
    else:
        return render(request, "viewPost.html", {'post': post})


def delete_post(request, postId):
    data = PropertyDB.objects.get(PropertyId=postId)
    data.delete()
    messages.error(request, "Post Removed..!!")
    return redirect(property_list)


def edit_post(request, postId):
    post = PropertyDB.objects.get(PropertyId=postId)
    if 'userid' in request.session:
        profile = RegistrationDB.objects.get(UserId=request.session['userid'])
        return render(request, "editPost.html", {'profile': profile, 'post': post})
    else:
        return render(request, "editPost.html", {'post': post})


def update_post(request, postId):
    if request.method == "POST":
        lo = request.POST.get('location')
        ty = request.POST.get('type')
        pu = request.POST.get('purpose')
        pr = request.POST.get('price')
        ph = request.POST.get('phone')
        ti = request.POST.get('title')
        de = request.POST.get('description')

        try:
            img = request.FILES['image']
            fs = FileSystemStorage()
            file = fs.save(img.name, img)
        except MultiValueDictKeyError:
            file = PropertyDB.objects.get(PropertyId=postId).Image
        PropertyDB.objects.filter(PropertyId=postId).update(Location=lo, Type=ty, Purpose=pu, Price=pr, Phone=ph, Title=ti, Description=de, Image=file)
        messages.success(request, "Post updated successfully..!!")
        return redirect(my_post)
    
class Feed(CreateView):
    template_name="feedback.html"
    model=Feedback
    form_class=Feedback_form
    success_url=reverse_lazy('home')

RealEstate/REApp/templates/feedback.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Feedback Form</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 500px;
            margin: 50px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            text-align: center;
            margin-bottom: 20px;
        }
        form {
            width: 100%;
        }
        label {
            display: block;
            margin-bottom: 8px;
        }
        input[type="text"],
        input[type="email"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
            resize: vertical; /* Allows vertical resizing */
            min-height: 150px; /* Minimum height of the textarea */
        }
        button[type="submit"] {
            background-color: #0ca855;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        button[type="submit"]:hover {
            background-color: #146105;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Feedback Form</h1>
        <form method="post">
            {% csrf_token %}
            <label for="id_Name">Name:</label>
            {{ form.Name }}
            <label for="id_Gmail">Email:</label>
            {{ form.Gmail }}
            <label for="id_Message">Message:</label>
            {{ form.Message }}
            <button type="submit">Submit</button>
        </form>
    </div>
</body>
</html>

RealEstate/REApp/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Login Page</title>
	<link href="{% static 'assets/img/icon-deal.png' %}" rel="icon" type="image/x-icon">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
	<!-- Main Content -->
	<div class="container">
		<div class="row main-content bg-success text-center">
			<div class="col-md-4 text-center company__info">
				<span class="company__logo"><h2><span class="fa fa-android"></span></h2></span>
				<h4 class="company_title"><img class="text-center" src="{% static 'assets/img/icon-deal.png' %}" alt="" srcset="" height="45px" width="45px">RealEstate</h4>
			</div>
			<div class="col-md-8 col-xs-12 col-sm-12 login_form ">
				<div class="container-fluid">
					<div class="row">
						<h2>Log In</h2>
					</div>
					<div class="row">
						<form class="form-group" method="post" action="{% url 'user_login' %}">
							{% csrf_token %}
							<div class="row">
								<input type="email" name="email" id="email" class="form__input" placeholder="Email">
							</div>
							<div class="row">
								<!-- <span class="fa fa-lock"></span> -->
								<input type="password" name="password" id="password" class="form__input" placeholder="Password">
							</div>
							<div class="row">
								<input type="submit" value="Login" class="btn">
							</div>
						</form>
					</div>
					<div class="row">
						<p>Don't have an account? <a href="{% url 'registration' %}">Register Here</a></p>
					</div>
				</div>
			</div>
		</div>
	</div>

	



</body>
<style>
		.main-content{
		width: 50%;
		border-radius: 20px;
		box-shadow: 0 5px 5px rgba(0,0,0,.4);
		margin: 5em auto;
		display: flex;
	}
	.company__info{
		background-color: #008080;
		border-top-left-radius: 20px;
		border-bottom-left-radius: 20px;
		display: flex;
		flex-direction: column;
		justify-content: center;
		color: #fff;
	}
	.fa-android{
		font-size:3em;
	}
	@media screen and (max-width: 640px) {
		.main-content{width: 90%;}
		.company__info{
			display: none;
		}
		.login_form{
			border-top-left-radius:20px;
			border-bottom-left-radius:20px;
		}
	}
	@media screen and (min-width: 642px) and (max-width:800px){
		.main-content{width: 70%;}
	}
	.row > h2{
		color:#008080;
	}
	.login_form{
		background-color: #fff;
		border-top-right-radius:20px;
		border-bottom-right-radius:20px;
		border-top:1px solid #ccc;
		border-right:1px solid #ccc;
	}
	form{
		padding: 0 2em;
	}
	.form__input{
		width: 100%;
		border:0px solid transparent;
		border-radius: 0;
		border-bottom: 1px solid #aaa;
		padding: 1em .5em .5em;
		padding-left: 2em;
		outline:none;
		margin:1.5em auto;
		transition: all .5s ease;
	}
	.form__input:focus{
		border-bottom-color: #008080;
		box-shadow: 0 0 5px rgba(0,80,80,.4);
		border-radius: 4px;
	}
	.btn{
		transition: all .5s ease;
		width: 70%;
		border-radius: 30px;
		color:#008080;
		font-weight: 600;
		background-color: #fff;
		border: 1px solid #008080;
		margin-top: 1.5em;
		margin-bottom: 1em;
	}
	.btn:hover, .btn:focus{
		background-color: #008080;
		color:#fff;
	}
</style>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

        {% if messages %}
            {% for i in messages %}
                {% if i.tags == 'warning' %}
                    <script>
                        swal('{{i}}','','warning');
                    </script>
                {% elif i.tags == 'error' %}
                    <script>
                        swal('{{i}}','','error');
                    </script>
                {% elif i.tags == 'success' %}
                    <script>
                        swal('{{i}}','','success');
                    </script>
                {% else %}
                    <script>
                        swal('{{i}}','','info');
                    </script>
                {% endif %}
            {% endfor %}
        {% endif %}

</html>

RealEstate/REApp/templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Register</title>
	<link href="{% static 'assets/img/icon-deal.png' %}" rel="icon" type="image/x-icon">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
	<!-- Main Content -->
	<div class="container">
		<div class="row main-content bg-success text-center">
			<div class="col-md-4 text-center company__info">

				<span class="company__logo"><h2><span class="fa fa-android"></span></h2></span>
				<h4 class="company_title"><img class="text-center" src="{% static 'assets/img/icon-deal.png' %}" alt="" srcset="" height="45px" width="45px">RealEstate</h4>
			</div>
			<div class="col-md-8 col-xs-12 col-sm-12 login_form ">
				<div class="container-fluid">
					<div class="row">
						<h4>New User Registration</h4>
					</div>
					<div class="row">
						<form class="form-group" method="post" action="{% url 'save_registration' %}">
							{% csrf_token %}

							<div class="row">
								<input type="text" name="name" id="name" class="form__input" placeholder="Full Name">
							</div>

							<div class="row">
								<input type="email" name="email" id="email" class="form__input" placeholder="Email Address">
							</div>

							<div class="row">
								<input type="password" name="password" id="password" class="form__input" placeholder="Password">
							</div>

							<div class="row">
								<div class="col">
									<div class="form-check">
									  <input class="form-check-input" type="radio" value="Buyer/Owner/Tenant" name="role" id="flexRadioDefault1">
									  <label class="form-check-label" for="flexRadioDefault1">
										Buyer/Owner/Tenant
									  </label>
									</div>
								</div>
								<div class="col">
									<div class="form-check text-start">
									  <input class="form-check-input" type="radio" value="Agent" name="role" id="flexRadioDefault2">
									  <label class="form-check-label" for="flexRadioDefault2">
										Agent
									  </label>
									</div>
								</div>
							</div>

							<div class="row">
								<input type="submit" value="Register" class="btn">
							</div>
						</form>
					</div>
					<div class="row">
						<p>Already Registered? <a href="{% url 'login' %}">Login Here</a></p>
					</div>
				</div>
			</div>
		</div>
	</div>



</body>
<style>
		.main-content{
		width: 50%;
		border-radius: 20px;
		box-shadow: 0 5px 5px rgba(0,0,0,.4);
		margin: 5em auto;
		display: flex;
	}
	.company__info{
		background-color: #008080;
		border-top-left-radius: 20px;
		border-bottom-left-radius: 20px;
		display: flex;
		flex-direction: column;
		justify-content: center;
		color: #fff;
	}
	.fa-android{
		font-size:3em;
	}
	@media screen and (max-width: 640px) {
		.main-content{width: 90%;}
		.company__info{
			display: none;
		}
		.login_form{
			border-top-left-radius:20px;
			border-bottom-left-radius:20px;
		}
	}
	@media screen and (min-width: 642px) and (max-width:800px){
		.main-content{width: 70%;}
	}
	.row > h4{
		color:#008080;
	}
	.login_form{
		background-color: #fff;
		border-top-right-radius:20px;
		border-bottom-right-radius:20px;
		border-top:1px solid #ccc;
		border-right:1px solid #ccc;
	}
	form{
		padding: 0 2em;
	}
	.form__input{
		width: 100%;
		border:0px solid transparent;
		border-radius: 0;
		border-bottom: 1px solid #aaa;
		padding: 1em .5em .5em;
		padding-left: 2em;
		outline:none;
		margin:1.5em auto;
		transition: all .5s ease;
	}
	.form__input:focus{
		border-bottom-color: #008080;
		box-shadow: 0 0 5px rgba(0,80,80,.4);
		border-radius: 4px;
	}
	.btn{
		transition: all .5s ease;
		width: 70%;
		border-radius: 30px;
		color:#008080;
		font-weight: 600;
		background-color: #fff;
		border: 1px solid #008080;
		margin-top: 1.5em;
		margin-bottom: 1em;
	}
	.btn:hover, .btn:focus{
		background-color: #008080;
		color:#fff;
	}
</style>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

        {% if messages %}
            {% for i in messages %}
                {% if i.tags == 'warning' %}
                    <script>
                        swal('{{i}}','','warning');
                    </script>
                {% elif i.tags == 'error' %}
                    <script>
                        swal('{{i}}','','error');
                    </script>
                {% elif i.tags == 'success' %}
                    <script>
                        swal('{{i}}','','success');
                    </script>
                {% else %}
                    <script>
                        swal('{{i}}','','info');
                    </script>
                {% endif %}
            {% endfor %}
        {% endif %}
</html>